Make the compile error from `const qubit&` argument more explicit (#5266)
Our quantum gates are declared to support `qubit &` (non-const type).

However, this check is performed rather late, e.g., in the
implementation (`oneQubitApply`).

This generated an unwieldy error message, which didn't really point to
the fact that user has a `const` qualifier.

For example, a reported case was

```
struct for_in_vector {
  auto operator()() __qpu__ {
    cudaq::qvector q(2);
    for (auto const& qubit : q) {
      x(qubit);
      x(qubit);
    }
  }
};
```

which resulted in a complex compile error chain, including `Cannot
operate on a qudit with Levels != 2`, etc.,

```
E           In file included from for_in_vector.cpp:12:
E           In file included from /opt/nvidia/cudaq/include/cudaq.h:14:
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:69:17: error: static assertion failed due to requirement 'std::conjunction<std::is_same<cudaq::qudit<2>, const cudaq::qudit<2>>>::value': Cannot operate on a qudit with Levels != 2
E              69 |   static_assert(std::conjunction<std::is_same<qubit, QubitArgs>...>::value,
E                 |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:172:1: note: in instantiation of function template specialization 'cudaq::oneQubitApply<cudaq::qubit_op::xOp, cudaq::base, const cudaq::qudit<2>>' requested here
E             172 | CUDAQ_QIS_ONE_TARGET_QUBIT_(x)
E                 | ^
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:148:5: note: expanded from macro 'CUDAQ_QIS_ONE_TARGET_QUBIT_'
E             148 |     oneQubitApply<qubit_op::NAME##Op, mod>(args...);                           \
E                 |     ^
E           for_in_vector.cpp:20:7: note: in instantiation of function template specialization 'cudaq::x<cudaq::base, const cudaq::qudit<2>>' requested here
E              20 |       x(qubit);
E                 |       ^
E           In file included from for_in_vector.cpp:12:
E           In file included from /opt/nvidia/cudaq/include/cudaq.h:14:
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:76:37: error: no matching function for call to 'qubitToQuditInfo'
E              76 |   std::vector<QuditInfo> quditInfos{qubitToQuditInfo(args)...};
E                 |                                     ^~~~~~~~~~~~~~~~
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:56:18: note: candidate function not viable: 1st argument ('const cudaq::qudit<2>') would lose const qualifier
E              56 | inline QuditInfo qubitToQuditInfo(qubit &q) { return {q.n_levels(), q.id()}; }
E                 |                  ^                ~~~~~~~~
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:77:36: error: no matching function for call to 'qubitIsNegative'
E              77 |   std::vector<bool> qubitIsNegated{qubitIsNegative(args)...};
E                 |                                    ^~~~~~~~~~~~~~~
E           /opt/nvidia/cudaq/include/cudaq/qis/qubit_qis.h:57:13: note: candidate function not viable: 1st argument ('const cudaq::qudit<2>') would lose const qualifier
E              57 | inline bool qubitIsNegative(qubit &q) { return q.is_negative(); }
E                 |             ^               ~~~~~~~~
E           error: C++ source has errors. nvq++ cannot proceed.
```

This PR adds an early catch for this case to output a proper compiler
error message.

---------

Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>