Fixing nested loop adjoint (#5228)
`cudaq.adjoint` failed on a kernel with a nested loop, even when the
kernel is perfectly reversible. The QFT in the Shor's algorithm notebook
hits this error as

```
loc(callsite(unknown at callsite("-":29:9 at "-":27:12))): error: 'arith.cmpi' op control-flow def-use not reversible.
loc(callsite(unknown at callsite("-":29:9 at "-":27:12))): error: 'cc.loop' op loop not reversed.
RuntimeError: could not autogenerate the adjoint of a kernel
```

Please see the issue #5223 for the root cause and the approach taken.
Fixes #5223

---------

Signed-off-by: Sachin Pisal <spisal@nvidia.com>