QCI integration (#3112)
* Temporary patch for QED-C debugging with NVIDIA.

Signed-off-by: qci-opensource <opensource@quantumcircuits.com>

* Add quantum device define

Signed-off-by: Anna Gringauze <agringauze@nvidia.com>

* Copy quantinuum gate set decomposition pass for QCI

Signed-off-by: Anna Gringauze <agringauze@nvidia.com>

* Added cmake build variable to make the target opt-in; enabled by default
* Updated tests to invoke target only if available.
* Added missing license header(s)
* More target tests
* Added the pass to expand measurements
* Use logging macros
* Build fix for the following issue -
   runtime/cudaq/platform/default/rest/helpers/qci/QCIServerHelper.cpp:248:20: error: unused structured binding declaration [-Werror=unused-variable]
* Potential build fix for the following issue -
   runtime/cudaq/platform/default/rest/helpers/qci/QCIServerHelper.cpp:259:29: error: invalid operands to binary expression ('const std::string' (aka 'const basic_string<char>') and 'const value_type' (aka 'const nlohmann::basic_json<>'))
* Added a mock server for QCI
* Basic Python tests
* Make spell checker happy
* Remove those target tests which don't have explicit measurement(s)
* Adding the new passes from PR#3305
* Addressing review comments - fixing typos
* Enable nightly integration tests for QCI

Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>

---------

Signed-off-by: qci-opensource <opensource@quantumcircuits.com>
Signed-off-by: Anna Gringauze <agringauze@nvidia.com>
Signed-off-by: Pradnya Khalate <pkhalate@nvidia.com>
Co-authored-by: Anna Gringauze <agringauze@nvidia.com>
Co-authored-by: Pradnya Khalate <pkhalate@nvidia.com>
Co-authored-by: Pradnya Khalate <148914294+khalatepradnya@users.noreply.github.com>