[CI] Update mpi4py version in `cudaq.ext.Dockerfile` (#3947)
<!--
Thanks for helping us improve CUDA-Q!

⚠️ The pull request title should be concise and understandable for all.
⚠️ If your pull request fixes an open issue, please link to the issue.

Checklist:
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
-->

### Description
<!-- Include relevant issues here, describe what changed and why -->

Publishing docker build is [failing
](https://github.com/NVIDIA/cuda-quantum/actions/runs/21952177366/job/63412887110#step:13:1485)with:

```
9.470         File "/tmp/pip-install-03vshwra/mpi4py_9df1dfe3e98e4e9ca972bf290b409a21/conf/mpidistutils.py", line 1002, in run
9.470           self.compiler = new_compiler(compiler=self.compiler,
9.470                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
9.470       TypeError: new_compiler() got an unexpected keyword argument 'dry_run'
9.470       [end of output]
```


This might be related to https://peps.pythondiscord.com/pep-0632/ 

`mpi4py` version 4+ doesn't have this code anymore. 
I can reproduce the pip failure locally if using `~=3.1`, while `~=4.1`
is working.
Hence, updating the mpi4py version in the dockerfile.

Signed-off-by: Thien Nguyen <thiennguyen@nvidia.com>